version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./backend/app:/code/app



  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - '/app/node_modules'
    ports:
      - '8080:8080'


